/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DatabaseIO.QuestionDAO;
import DatabaseIO.TestDAO;
import DatabaseIO.Test_QuestionDAO;
import Model.Question;
import Model.Test;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Vector;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mrloc
 */
public class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminForm
     */
    public AdminForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelAccount = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanelAdminAccount = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStudentAc = new javax.swing.JTable();
        jPanelStudentAccount = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTeacherAc = new javax.swing.JTable();
        jButtonAddListAc = new javax.swing.JButton();
        jButtonAddAc = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanelLesson = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanelChapter = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableChapter = new javax.swing.JTable();
        jButtonAddChapter = new javax.swing.JButton();
        jButtonEditChapter = new javax.swing.JButton();
        jButtonDeleteChapter = new javax.swing.JButton();
        jPanelListLesson = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableLesson = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxChapter = new javax.swing.JComboBox<String>();
        jButtonAddLesson = new javax.swing.JButton();
        jButtonEditLesson = new javax.swing.JButton();
        jButtonDeleteLesson = new javax.swing.JButton();
        jPanelQuestion = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxListChapter = new javax.swing.JComboBox<String>();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxListLesson = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxDiff = new javax.swing.JComboBox<String>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelExam = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanelTests = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableTests = new javax.swing.JTable();
        jButtonAddTest = new javax.swing.JButton();
        jButtonEditTest = new javax.swing.JButton();
        jButtonDeleteTest = new javax.swing.JButton();
        jPanelTestQuestion = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableQuestions = new javax.swing.JTable();
        jButtonAddQuestion = new javax.swing.JButton();
        jButtonEditQuestion = new javax.swing.JButton();
        jButtonDeleteQuestion = new javax.swing.JButton();
        jPanelStatistic = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelAccount.setLayout(new java.awt.BorderLayout());

        jPanelAdminAccount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelAdminAccount.setPreferredSize(new java.awt.Dimension(500, 572));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tài khoản sinh viên");

        jTableStudentAc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Username", "Họ và tên", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableStudentAc);
        if (jTableStudentAc.getColumnModel().getColumnCount() > 0) {
            jTableStudentAc.getColumnModel().getColumn(0).setMinWidth(40);
            jTableStudentAc.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTableStudentAc.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        javax.swing.GroupLayout jPanelAdminAccountLayout = new javax.swing.GroupLayout(jPanelAdminAccount);
        jPanelAdminAccount.setLayout(jPanelAdminAccountLayout);
        jPanelAdminAccountLayout.setHorizontalGroup(
            jPanelAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminAccountLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );
        jPanelAdminAccountLayout.setVerticalGroup(
            jPanelAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminAccountLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelStudentAccount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tài khoản giáo viên");

        jTableTeacherAc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Username", "Họ và tên", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableTeacherAc);
        if (jTableTeacherAc.getColumnModel().getColumnCount() > 0) {
            jTableTeacherAc.getColumnModel().getColumn(0).setMinWidth(40);
            jTableTeacherAc.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTableTeacherAc.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        javax.swing.GroupLayout jPanelStudentAccountLayout = new javax.swing.GroupLayout(jPanelStudentAccount);
        jPanelStudentAccount.setLayout(jPanelStudentAccountLayout);
        jPanelStudentAccountLayout.setHorizontalGroup(
            jPanelStudentAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStudentAccountLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );
        jPanelStudentAccountLayout.setVerticalGroup(
            jPanelStudentAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStudentAccountLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelAdminAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelStudentAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelStudentAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAdminAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        jButtonAddListAc.setText("Thêm danh sách tài khoản sinh viên bằng file Excel");

        jButtonAddAc.setText("Thêm 1 tài khoản");

        jButton1.setText("Vô hiệu hóa | Kích hoạt");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jButtonAddListAc)
                .addGap(91, 91, 91)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAddAc)
                .addGap(136, 136, 136))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddListAc)
                    .addComponent(jButtonAddAc)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanelAccount.add(jPanel2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Quản lý tài khoản", jPanelAccount);

        jPanelLesson.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanelChapter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelChapter.setPreferredSize(new java.awt.Dimension(497, 579));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Danh sách chương");

        jTableChapter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Chương", "Tên chương"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableChapter);
        if (jTableChapter.getColumnModel().getColumnCount() > 0) {
            jTableChapter.getColumnModel().getColumn(0).setMinWidth(60);
            jTableChapter.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTableChapter.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        jButtonAddChapter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonAddChapter.setText("Thêm chương");

        jButtonEditChapter.setText("Sửa chương");

        jButtonDeleteChapter.setText("Xóa chương");

        javax.swing.GroupLayout jPanelChapterLayout = new javax.swing.GroupLayout(jPanelChapter);
        jPanelChapter.setLayout(jPanelChapterLayout);
        jPanelChapterLayout.setHorizontalGroup(
            jPanelChapterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
            .addGroup(jPanelChapterLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelChapterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAddChapter, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEditChapter, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButtonDeleteChapter, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelChapterLayout.setVerticalGroup(
            jPanelChapterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChapterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanelChapterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddChapter)
                    .addComponent(jButtonEditChapter)
                    .addComponent(jButtonDeleteChapter))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanelChapter, java.awt.BorderLayout.LINE_START);

        jPanelListLesson.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Danh sách bài");

        jTableLesson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bài", "Tên bài"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableLesson);
        if (jTableLesson.getColumnModel().getColumnCount() > 0) {
            jTableLesson.getColumnModel().getColumn(0).setMinWidth(60);
            jTableLesson.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTableLesson.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Chọn chương");

        jComboBoxChapter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonAddLesson.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonAddLesson.setText("Thêm bài");

        jButtonEditLesson.setText("Sửa bài");

        jButtonDeleteLesson.setText("Xóa bài");

        javax.swing.GroupLayout jPanelListLessonLayout = new javax.swing.GroupLayout(jPanelListLesson);
        jPanelListLesson.setLayout(jPanelListLessonLayout);
        jPanelListLessonLayout.setHorizontalGroup(
            jPanelListLessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
            .addGroup(jPanelListLessonLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelListLessonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListLessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListLessonLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxChapter, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelListLessonLayout.createSequentialGroup()
                        .addComponent(jButtonAddLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jButtonDeleteLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanelListLessonLayout.setVerticalGroup(
            jPanelListLessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListLessonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(jPanelListLessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxChapter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanelListLessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddLesson)
                    .addComponent(jButtonEditLesson)
                    .addComponent(jButtonDeleteLesson))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanelListLesson, java.awt.BorderLayout.CENTER);

        jPanelLesson.add(jPanel3, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Quản lý chương trình học", jPanelLesson);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Chương");

        jComboBoxListChapter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Bài");

        jComboBoxListLesson.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Mức độ");

        jComboBoxDiff.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dễ", "Trung Bình", "Khó" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelQuestionLayout = new javax.swing.GroupLayout(jPanelQuestion);
        jPanelQuestion.setLayout(jPanelQuestionLayout);
        jPanelQuestionLayout.setHorizontalGroup(
            jPanelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuestionLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxListChapter, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxListLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxDiff, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanelQuestionLayout.setVerticalGroup(
            jPanelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxListChapter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxListLesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxDiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Quản lý câu hỏi", jPanelQuestion);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanelTests.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelTests.setPreferredSize(new java.awt.Dimension(497, 579));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Danh sách đề thi");

        jTableTests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã đề", "Số câu", "Thời gian", "Độ khó"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTests.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableTests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTestsMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTableTests);
        if (jTableTests.getColumnModel().getColumnCount() > 0) {
            jTableTests.getColumnModel().getColumn(0).setMinWidth(60);
            jTableTests.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTableTests.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        jButtonAddTest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonAddTest.setText("Thêm đề thi");
        jButtonAddTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTestActionPerformed(evt);
            }
        });

        jButtonEditTest.setText("Sửa đề thi");

        jButtonDeleteTest.setText("Xóa đề thi");

        javax.swing.GroupLayout jPanelTestsLayout = new javax.swing.GroupLayout(jPanelTests);
        jPanelTests.setLayout(jPanelTestsLayout);
        jPanelTestsLayout.setHorizontalGroup(
            jPanelTestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
            .addGroup(jPanelTestsLayout.createSequentialGroup()
                .addGroup(jPanelTestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTestsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAddTest, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditTest, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jButtonDeleteTest, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTestsLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelTestsLayout.setVerticalGroup(
            jPanelTestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTestsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanelTestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddTest)
                    .addComponent(jButtonEditTest)
                    .addComponent(jButtonDeleteTest))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(jPanelTests, java.awt.BorderLayout.LINE_START);

        jPanelTestQuestion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Danh sách câu hỏi");

        jTableQuestions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Câu hỏi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTableQuestions);
        if (jTableQuestions.getColumnModel().getColumnCount() > 0) {
            jTableQuestions.getColumnModel().getColumn(0).setMinWidth(60);
            jTableQuestions.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTableQuestions.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        jButtonAddQuestion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonAddQuestion.setText("Thêm câu hỏi");

        jButtonEditQuestion.setText("Sửa câu hỏi");

        jButtonDeleteQuestion.setText("Xóa câu hỏi");

        javax.swing.GroupLayout jPanelTestQuestionLayout = new javax.swing.GroupLayout(jPanelTestQuestion);
        jPanelTestQuestion.setLayout(jPanelTestQuestionLayout);
        jPanelTestQuestionLayout.setHorizontalGroup(
            jPanelTestQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
            .addGroup(jPanelTestQuestionLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelTestQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAddQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEditQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButtonDeleteQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanelTestQuestionLayout.setVerticalGroup(
            jPanelTestQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTestQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(74, 74, 74)
                .addGroup(jPanelTestQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddQuestion)
                    .addComponent(jButtonEditQuestion)
                    .addComponent(jButtonDeleteQuestion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(jPanelTestQuestion, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanelExamLayout = new javax.swing.GroupLayout(jPanelExam);
        jPanelExam.setLayout(jPanelExamLayout);
        jPanelExamLayout.setHorizontalGroup(
            jPanelExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
            .addGroup(jPanelExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelExamLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 995, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelExamLayout.setVerticalGroup(
            jPanelExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
            .addGroup(jPanelExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelExamLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Quản lý đề thi", jPanelExam);

        javax.swing.GroupLayout jPanelStatisticLayout = new javax.swing.GroupLayout(jPanelStatistic);
        jPanelStatistic.setLayout(jPanelStatisticLayout);
        jPanelStatisticLayout.setHorizontalGroup(
            jPanelStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        jPanelStatisticLayout.setVerticalGroup(
            jPanelStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Thống kê", jPanelStatistic);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn thoát chương trình?", "Xác nhận thoát", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (input == 0) {
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            LoginForm f = new LoginForm();
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
        }
        else{
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing
    /*Form Load*/
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        testsLoad();
    }//GEN-LAST:event_formWindowOpened

    private void jTableTestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTestsMouseClicked
        int row = jTableTests.getSelectedRow();
        if(row>=0){
            int idTest = (Integer)jTableTests.getValueAt(row, 0);
            testQuestionLoad(idTest);
        }
            
    }//GEN-LAST:event_jTableTestsMouseClicked

    private void jButtonAddTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTestActionPerformed
        addTest();
    }//GEN-LAST:event_jButtonAddTestActionPerformed
    
    void testsLoad()
    {
        DefaultTableModel testModel = new DefaultTableModel();
        Vector header = new Vector();
        header.add("ID đề");
        header.add("Mã đề");
        header.add("Số câu hỏi");
        header.add("Thời gian");
        header.add("Độ khó");
        testModel.setColumnIdentifiers(header);
        
        TestDAO testDao = new TestDAO();
        List<Test> fullTest = testDao.getFullListTest();
        for (int i = 0; i < fullTest.size(); i++) {
            Test test = fullTest.get(i);
            Vector row = new Vector();
            row.add(test.getTest_ID());
            row.add(test.getTest_Code());
            row.add(test.getNumber_Of_Question());
            row.add(test.getTime());
            row.add(test.getLevel());
            testModel.addRow(row);
        }
        jTableTests.setModel(testModel);
    }
    void testQuestionLoad(int idTest)
    {
        DefaultTableModel questionsModel = new DefaultTableModel();
        Vector header = new Vector();
        header.add("STT");
        header.add("Câu hỏi");
        questionsModel.setColumnIdentifiers(header);
        
        QuestionDAO questionsDao = new QuestionDAO();
        List<Question> listQuestions = questionsDao.getQuestionByIdTest(idTest);
        
        System.out.println(listQuestions.size());
        for (int i = 0; i < listQuestions.size(); i++) {
            Question question = listQuestions.get(i);
            Vector row = new Vector();
            row.add(i+1);
            row.add(question.getQuestion());
            questionsModel.addRow(row);
        }
        
        jTableQuestions.setModel(questionsModel);
    }
    void addTest(){
        TestDAO testDAO = new TestDAO();
        Test t = new Test("TestCode", 4, 20, 1, true, true);
        if(testDAO.insertTest(t)){
            addTestQuestionRandom(2,1);
            addTestQuestionRandom(2,2);
            addTestQuestionRandom(2,3);
        }
    }
    void addTestQuestion(int idQuestion){
        Test_QuestionDAO tqDao = new Test_QuestionDAO();
        TestDAO testDAO = new TestDAO();
        int idTestPre = testDAO.getMaxIdTest();//get new id Test by get max of idTest
        while(true){
            if(tqDao.insertTestQuestion(idTestPre, idQuestion))
                break;
        }
    }
    void addTestQuestionRandom(int amountRandom, int level){//By Level
        QuestionDAO questionDAO = new QuestionDAO();
        List<Question> listAdded = new ArrayList<Question>();
        List<Question> listQuestions = new ArrayList<Question>();
        
        listQuestions = questionDAO.getQuestionByLevel(level);
        
        int minRange=questionDAO.getMinIdQuestion(level);
        int maxRange=questionDAO.getMaxIdQuestion(level);
        do{
            Random r = new Random();
            int idQuest = minRange+ r.nextInt(maxRange-minRange+1);//just has random from 0 :V
            Question q = new Question();
                q.setQuestion_ID(idQuest);
            if(!listAdded.contains(q)&&listQuestions.contains(q)){
                listAdded.add(q);
                addTestQuestion(idQuest);
            }
        }
        while(listAdded.size()<amountRandom);
        testsLoad();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddAc;
    private javax.swing.JButton jButtonAddChapter;
    private javax.swing.JButton jButtonAddLesson;
    private javax.swing.JButton jButtonAddListAc;
    private javax.swing.JButton jButtonAddQuestion;
    private javax.swing.JButton jButtonAddTest;
    private javax.swing.JButton jButtonDeleteChapter;
    private javax.swing.JButton jButtonDeleteLesson;
    private javax.swing.JButton jButtonDeleteQuestion;
    private javax.swing.JButton jButtonDeleteTest;
    private javax.swing.JButton jButtonEditChapter;
    private javax.swing.JButton jButtonEditLesson;
    private javax.swing.JButton jButtonEditQuestion;
    private javax.swing.JButton jButtonEditTest;
    private javax.swing.JComboBox<String> jComboBoxChapter;
    private javax.swing.JComboBox<String> jComboBoxDiff;
    private javax.swing.JComboBox<String> jComboBoxListChapter;
    private javax.swing.JComboBox<String> jComboBoxListLesson;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelAccount;
    private javax.swing.JPanel jPanelAdminAccount;
    private javax.swing.JPanel jPanelChapter;
    private javax.swing.JPanel jPanelExam;
    private javax.swing.JPanel jPanelLesson;
    private javax.swing.JPanel jPanelListLesson;
    private javax.swing.JPanel jPanelQuestion;
    private javax.swing.JPanel jPanelStatistic;
    private javax.swing.JPanel jPanelStudentAccount;
    private javax.swing.JPanel jPanelTestQuestion;
    private javax.swing.JPanel jPanelTests;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableChapter;
    private javax.swing.JTable jTableLesson;
    private javax.swing.JTable jTableQuestions;
    private javax.swing.JTable jTableStudentAc;
    private javax.swing.JTable jTableTeacherAc;
    private javax.swing.JTable jTableTests;
    // End of variables declaration//GEN-END:variables
}
