/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DatabaseIO.AnswerDAO;
import DatabaseIO.ChapterDAO;
import DatabaseIO.LessonDAO;
import DatabaseIO.QuestionDAO;
import Model.Answer;
import Model.Chapter;
import Model.Lesson;
import Model.Question;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mrloc
 */
public class AdminForm extends javax.swing.JFrame {
    private ArrayList<Question> listQ;
    DefaultTableModel model;
    private int selectedIndex;
    /**
     * Creates new form AdminForm
     */
    public AdminForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        model = (DefaultTableModel) jTableQuestion.getModel();
        showChapterCombobox();
        showLessonCombobox();
        showTableQuestion();
    }
    
    // hiển thị thông tin ra bảng
    public void showTableQuestion(){
        listQ = new QuestionDAO().getListQuestion();
        Lesson l = new Lesson();
        Chapter c = new Chapter();
        model.setRowCount(0); //reset nội dung bảng
        for(Question q : listQ){
            String Lv = "Dễ";
            if(q.getLevel() == 2){
                Lv = "Trung bình";
            }
            if(q.getLevel() == 3){
                Lv = "Khó";
            }
            l = new LessonDAO().getLessonByLesson_ID(q.getLesson());
            c = new ChapterDAO().getChapterByChapter_ID(l.getChapter());
            model.addRow(new Object[]{
                q.getQuestion_ID(), q.getQuestion(), Lv, c.getChapter(), l.getLesson()
            });
        }
    }
    // hiển thị chương lên combobox
    public void showChapterCombobox(){
        cbbChapter.addItem("Tất cả");
        ArrayList<Chapter> listC = new ArrayList<Chapter>();
        listC = new ChapterDAO().getListChapter();
        for (Chapter chapter : listC) {
            cbbChapter.addItem(String.valueOf(chapter.getChapter()));
        }
    }
    // hiển thị bài lên combobox
    public void showLessonCombobox(){
        ArrayList<Lesson> listL = new ArrayList<Lesson>();
        listL = new LessonDAO().getListLesson();
        for (Lesson lesson : listL) {
            cbbLesson.addItem(String.valueOf(lesson.getLesson()));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelAccount = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanelAdminAccount = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStudentAc = new javax.swing.JTable();
        jPanelStudentAccount = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTeacherAc = new javax.swing.JTable();
        jButtonAddListAc = new javax.swing.JButton();
        jButtonAddAc = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanelLesson = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanelChapter = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableChapter = new javax.swing.JTable();
        jButtonAddChapter = new javax.swing.JButton();
        jButtonEditChapter = new javax.swing.JButton();
        jButtonDeleteChapter = new javax.swing.JButton();
        jPanelListLesson = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableLesson = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxChapter = new javax.swing.JComboBox<>();
        jButtonAddLesson = new javax.swing.JButton();
        jButtonEditLesson = new javax.swing.JButton();
        jButtonDeleteLesson = new javax.swing.JButton();
        jPanelQuestion = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbbChapter = new javax.swing.JComboBox<>();
        cbbLesson = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxDiff = new javax.swing.JComboBox<>();
        btnLoc = new javax.swing.JButton();
        btnAddQt = new javax.swing.JButton();
        btnEditQt = new javax.swing.JButton();
        btnDeleteQt = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableQuestion = new javax.swing.JTable();
        btnViewAns = new javax.swing.JButton();
        jPanelExam = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanelTests = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableTests = new javax.swing.JTable();
        jButtonAddTest = new javax.swing.JButton();
        jButtonEditTest = new javax.swing.JButton();
        jButtonDeleteTest = new javax.swing.JButton();
        jPanelTestQuestion = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableQuestions = new javax.swing.JTable();
        jButtonAddQuestion = new javax.swing.JButton();
        jButtonEditQuestion = new javax.swing.JButton();
        jButtonDeleteQuestion = new javax.swing.JButton();
        jPanelStatistic = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelAccount.setLayout(new java.awt.BorderLayout());

        jPanelAdminAccount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelAdminAccount.setPreferredSize(new java.awt.Dimension(500, 572));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tài khoản sinh viên");

        jTableStudentAc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Username", "Họ và tên", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableStudentAc);
        if (jTableStudentAc.getColumnModel().getColumnCount() > 0) {
            jTableStudentAc.getColumnModel().getColumn(0).setMinWidth(40);
            jTableStudentAc.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTableStudentAc.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        javax.swing.GroupLayout jPanelAdminAccountLayout = new javax.swing.GroupLayout(jPanelAdminAccount);
        jPanelAdminAccount.setLayout(jPanelAdminAccountLayout);
        jPanelAdminAccountLayout.setHorizontalGroup(
            jPanelAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminAccountLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );
        jPanelAdminAccountLayout.setVerticalGroup(
            jPanelAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminAccountLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelStudentAccount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tài khoản giáo viên");

        jTableTeacherAc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Username", "Họ và tên", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableTeacherAc);
        if (jTableTeacherAc.getColumnModel().getColumnCount() > 0) {
            jTableTeacherAc.getColumnModel().getColumn(0).setMinWidth(40);
            jTableTeacherAc.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTableTeacherAc.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        javax.swing.GroupLayout jPanelStudentAccountLayout = new javax.swing.GroupLayout(jPanelStudentAccount);
        jPanelStudentAccount.setLayout(jPanelStudentAccountLayout);
        jPanelStudentAccountLayout.setHorizontalGroup(
            jPanelStudentAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStudentAccountLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );
        jPanelStudentAccountLayout.setVerticalGroup(
            jPanelStudentAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStudentAccountLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelAdminAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelStudentAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelStudentAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAdminAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        jButtonAddListAc.setText("Thêm danh sách tài khoản sinh viên bằng file Excel");

        jButtonAddAc.setText("Thêm 1 tài khoản");

        jButton1.setText("Vô hiệu hóa | Kích hoạt");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jButtonAddListAc)
                .addGap(91, 91, 91)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAddAc)
                .addGap(136, 136, 136))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddListAc)
                    .addComponent(jButtonAddAc)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanelAccount.add(jPanel2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Quản lý tài khoản", jPanelAccount);

        jPanelLesson.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanelChapter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelChapter.setPreferredSize(new java.awt.Dimension(497, 579));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Danh sách chương");

        jTableChapter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Chương", "Tên chương"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableChapter);
        if (jTableChapter.getColumnModel().getColumnCount() > 0) {
            jTableChapter.getColumnModel().getColumn(0).setMinWidth(60);
            jTableChapter.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTableChapter.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        jButtonAddChapter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonAddChapter.setText("Thêm chương");

        jButtonEditChapter.setText("Sửa chương");

        jButtonDeleteChapter.setText("Xóa chương");

        javax.swing.GroupLayout jPanelChapterLayout = new javax.swing.GroupLayout(jPanelChapter);
        jPanelChapter.setLayout(jPanelChapterLayout);
        jPanelChapterLayout.setHorizontalGroup(
            jPanelChapterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
            .addGroup(jPanelChapterLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelChapterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAddChapter, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEditChapter, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButtonDeleteChapter, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelChapterLayout.setVerticalGroup(
            jPanelChapterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChapterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanelChapterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddChapter)
                    .addComponent(jButtonEditChapter)
                    .addComponent(jButtonDeleteChapter))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanelChapter, java.awt.BorderLayout.LINE_START);

        jPanelListLesson.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Danh sách bài");

        jTableLesson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bài", "Tên bài"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableLesson);
        if (jTableLesson.getColumnModel().getColumnCount() > 0) {
            jTableLesson.getColumnModel().getColumn(0).setMinWidth(60);
            jTableLesson.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTableLesson.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Chọn chương");

        jComboBoxChapter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonAddLesson.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonAddLesson.setText("Thêm bài");

        jButtonEditLesson.setText("Sửa bài");

        jButtonDeleteLesson.setText("Xóa bài");

        javax.swing.GroupLayout jPanelListLessonLayout = new javax.swing.GroupLayout(jPanelListLesson);
        jPanelListLesson.setLayout(jPanelListLessonLayout);
        jPanelListLessonLayout.setHorizontalGroup(
            jPanelListLessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
            .addGroup(jPanelListLessonLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelListLessonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListLessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListLessonLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxChapter, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelListLessonLayout.createSequentialGroup()
                        .addComponent(jButtonAddLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jButtonDeleteLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanelListLessonLayout.setVerticalGroup(
            jPanelListLessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListLessonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(jPanelListLessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxChapter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanelListLessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddLesson)
                    .addComponent(jButtonEditLesson)
                    .addComponent(jButtonDeleteLesson))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanelListLesson, java.awt.BorderLayout.CENTER);

        jPanelLesson.add(jPanel3, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Quản lý chương trình học", jPanelLesson);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Chương:");

        cbbChapter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChapterActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Bài:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Mức độ:");

        jComboBoxDiff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Dễ", "Trung Bình", "Khó" }));

        btnLoc.setText("Lọc");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        btnAddQt.setText("Thêm mới");
        btnAddQt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddQtActionPerformed(evt);
            }
        });

        btnEditQt.setText("Sửa");
        btnEditQt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditQtActionPerformed(evt);
            }
        });

        btnDeleteQt.setText("Xóa");
        btnDeleteQt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteQtActionPerformed(evt);
            }
        });

        jTableQuestion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableQuestion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Question ID", "Question", "Level", "Chapter", "Lesson"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableQuestion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableQuestion.setDragEnabled(true);
        jTableQuestion.setFocusable(false);
        jTableQuestion.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableQuestion.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableQuestion.setShowGrid(true);
        jTableQuestion.setShowHorizontalLines(false);
        jTableQuestion.setSurrendersFocusOnKeystroke(true);
        jScrollPane5.setViewportView(jTableQuestion);
        if (jTableQuestion.getColumnModel().getColumnCount() > 0) {
            jTableQuestion.getColumnModel().getColumn(0).setMinWidth(100);
            jTableQuestion.getColumnModel().getColumn(0).setMaxWidth(100);
            jTableQuestion.getColumnModel().getColumn(2).setMinWidth(100);
            jTableQuestion.getColumnModel().getColumn(2).setMaxWidth(100);
            jTableQuestion.getColumnModel().getColumn(3).setMinWidth(100);
            jTableQuestion.getColumnModel().getColumn(3).setMaxWidth(100);
            jTableQuestion.getColumnModel().getColumn(4).setMinWidth(100);
            jTableQuestion.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        btnViewAns.setText("Xem câu trả lời");
        btnViewAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAnsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelQuestionLayout = new javax.swing.GroupLayout(jPanelQuestion);
        jPanelQuestion.setLayout(jPanelQuestionLayout);
        jPanelQuestionLayout.setHorizontalGroup(
            jPanelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
            .addGroup(jPanelQuestionLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelQuestionLayout.createSequentialGroup()
                        .addComponent(btnAddQt)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditQt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteQt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelQuestionLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbbChapter, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQuestionLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxDiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnViewAns))
                .addContainerGap(393, Short.MAX_VALUE))
        );
        jPanelQuestionLayout.setVerticalGroup(
            jPanelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbbChapter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbbLesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxDiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoc))
                .addGap(18, 18, 18)
                .addGroup(jPanelQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddQt)
                    .addComponent(btnDeleteQt)
                    .addComponent(btnViewAns)
                    .addComponent(btnEditQt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Quản lý câu hỏi", jPanelQuestion);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanelTests.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelTests.setPreferredSize(new java.awt.Dimension(497, 579));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Danh sách đề thi");

        jTableTests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã đề", "Số câu", "Thời gian", "Độ khó"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTests.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane6.setViewportView(jTableTests);
        if (jTableTests.getColumnModel().getColumnCount() > 0) {
            jTableTests.getColumnModel().getColumn(0).setMinWidth(60);
            jTableTests.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTableTests.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        jButtonAddTest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonAddTest.setText("Thêm đề thi");

        jButtonEditTest.setText("Sửa đề thi");

        jButtonDeleteTest.setText("Xóa đề thi");

        javax.swing.GroupLayout jPanelTestsLayout = new javax.swing.GroupLayout(jPanelTests);
        jPanelTests.setLayout(jPanelTestsLayout);
        jPanelTestsLayout.setHorizontalGroup(
            jPanelTestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
            .addGroup(jPanelTestsLayout.createSequentialGroup()
                .addGroup(jPanelTestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTestsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAddTest, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditTest, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jButtonDeleteTest, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTestsLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelTestsLayout.setVerticalGroup(
            jPanelTestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTestsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanelTestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddTest)
                    .addComponent(jButtonEditTest)
                    .addComponent(jButtonDeleteTest))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(jPanelTests, java.awt.BorderLayout.LINE_START);

        jPanelTestQuestion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Danh sách câu hỏi");

        jTableQuestions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Câu hỏi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTableQuestions);
        if (jTableQuestions.getColumnModel().getColumnCount() > 0) {
            jTableQuestions.getColumnModel().getColumn(0).setMinWidth(60);
            jTableQuestions.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTableQuestions.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        jButtonAddQuestion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonAddQuestion.setText("Thêm câu hỏi");

        jButtonEditQuestion.setText("Sửa câu hỏi");

        jButtonDeleteQuestion.setText("Xóa câu hỏi");

        javax.swing.GroupLayout jPanelTestQuestionLayout = new javax.swing.GroupLayout(jPanelTestQuestion);
        jPanelTestQuestion.setLayout(jPanelTestQuestionLayout);
        jPanelTestQuestionLayout.setHorizontalGroup(
            jPanelTestQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
            .addGroup(jPanelTestQuestionLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelTestQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAddQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEditQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButtonDeleteQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanelTestQuestionLayout.setVerticalGroup(
            jPanelTestQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTestQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(74, 74, 74)
                .addGroup(jPanelTestQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddQuestion)
                    .addComponent(jButtonEditQuestion)
                    .addComponent(jButtonDeleteQuestion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(jPanelTestQuestion, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanelExamLayout = new javax.swing.GroupLayout(jPanelExam);
        jPanelExam.setLayout(jPanelExamLayout);
        jPanelExamLayout.setHorizontalGroup(
            jPanelExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
            .addGroup(jPanelExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelExamLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 995, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelExamLayout.setVerticalGroup(
            jPanelExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
            .addGroup(jPanelExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelExamLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Quản lý đề thi", jPanelExam);

        javax.swing.GroupLayout jPanelStatisticLayout = new javax.swing.GroupLayout(jPanelStatistic);
        jPanelStatistic.setLayout(jPanelStatisticLayout);
        jPanelStatisticLayout.setHorizontalGroup(
            jPanelStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        jPanelStatisticLayout.setVerticalGroup(
            jPanelStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Thống kê", jPanelStatistic);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int input = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn thoát chương trình?", "Xác nhận thoát", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (input == 0) {
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            LoginForm f = new LoginForm();
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
        }
        else{
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing
    /*Form Load*/
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
    }//GEN-LAST:event_formWindowOpened

    // lọc câu hỏi theo độ khó
    private void getQuestionByDiff(int d){
        listQ = new QuestionDAO().getListQuestion();
        model.setRowCount(0);
        for(Question q : listQ){
            if(d == 0){
                showTableQuestion();
            } else{
                if(q.getLevel() == d){
                    String Lv = "Dễ";
                    if(q.getLevel() == 2){
                        Lv = "Trung bình";
                    }
                    if(q.getLevel() == 3){
                        Lv = "Khó";
                    }
                    model.addRow(new Object[]{
                        q.getQuestion_ID(), q.getQuestion(), Lv, q.getLesson()
                    });
                }
            }
        }
    }   
    // lọc câu hỏi theo lesson
    private void getQuestionByLesson(int l){
        listQ = new QuestionDAO().getListQuestion();
        model.setRowCount(0);
        for(Question q : listQ){
            if(l < 1){
                showTableQuestion();
            } else{
                if(q.getLesson() == l){
                    String Lv = "Dễ";
                    if(q.getLevel() == 2){
                        Lv = "Trung bình";
                    }
                    if(q.getLevel() == 3){
                        Lv = "Khó";
                    }
                    model.addRow(new Object[]{
                        q.getQuestion_ID(), q.getQuestion(), Lv, q.getLesson()
                    });
                }
            }
        }
    }
    // lọc câu hỏi theo độ khó và bài
    private void getQuestionByLessAndDiff(int l, int d){
        listQ = new QuestionDAO().getListQuestion();
            model.setRowCount(0);
            for(Question q : listQ){
                if(q.getLevel() == d && q.getLesson() == l){
                    String Lv = "Dễ";
                    if(q.getLevel() == 2){
                        Lv = "Trung bình";
                    }
                    if(q.getLevel() == 3){
                        Lv = "Khó";
                    }
                    model.addRow(new Object[]{
                        q.getQuestion_ID(), q.getQuestion(), Lv, q.getLesson()
                    });
                }
            }
    }
    
    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        int indexLess = cbbLesson.getSelectedIndex();
        int indexDiff = jComboBoxDiff.getSelectedIndex();
        if(indexDiff == 0 && indexLess == 0){
            showTableQuestion();
        } else if(indexDiff == 0 && indexLess > 0){
            int Less = Integer.parseInt(cbbLesson.getSelectedItem().toString());
            getQuestionByLesson(Less);
        } else if(indexLess == 0 && indexDiff != 0){
            getQuestionByDiff(indexDiff);
        } else{
            int Less = Integer.parseInt(cbbLesson.getSelectedItem().toString());
            getQuestionByLessAndDiff(Less, indexDiff);
        }
    }//GEN-LAST:event_btnLocActionPerformed

    private void btnAddQtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddQtActionPerformed
        AddQuestionDialog f = new AddQuestionDialog(this, rootPaneCheckingEnabled);
        f.setVisible(true);
    }//GEN-LAST:event_btnAddQtActionPerformed
    
    private void getOldData(){
        selectedIndex = jTableQuestion.getSelectedRow();
        if(listQ.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,
                "Hãy nhập thêm câu hỏi rồi sửa!");
        } else if(selectedIndex == -1) {
            JOptionPane.showMessageDialog(rootPane,
                "Hãy chọn dòng có câu hỏi cần sửa rồi ấn Sửa!");
        } else {
            EditQuestionDialog edit = new EditQuestionDialog(this, rootPaneCheckingEnabled);
            edit.showChapterCombobox();
            Question q = new Question();
            q = listQ.get(selectedIndex);
            edit.getOldQuestionData(q);
            List<Answer> listAsw = new ArrayList<>();
            listAsw = new AnswerDAO().list(q.getQuestion_ID());
            edit.getOldAnswerData(listAsw.get(0), listAsw.get(1), listAsw.get(2), listAsw.get(3));
            edit.setVisible(true);
        }
    }
    private void btnEditQtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditQtActionPerformed
        getOldData();
    }//GEN-LAST:event_btnEditQtActionPerformed

    private void btnDeleteQtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteQtActionPerformed
        selectedIndex = jTableQuestion.getSelectedRow();
        if(listQ.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,
                "Hãy nhập thêm câu hỏi rồi xóa!");
        } else if(selectedIndex == -1) {
            JOptionPane.showMessageDialog(rootPane,
                "Hãy chọn dòng có câu hỏi cần xóa rồi ấn Xóa!");
        } else {
            int dialogResult = JOptionPane.showConfirmDialog(rootPane,
                "Bạn chắc chắn muốn xóa câu hỏi này?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if(dialogResult == 0){
                try {
                    int id = listQ.get(selectedIndex).getQuestion_ID();
                    if(new QuestionDAO().deleteQuestion(id)){
                        showTableQuestion();
                        JOptionPane.showMessageDialog(jPanelAccount, "Xóa thành công!");
                    } else{
                        JOptionPane.showMessageDialog(jPanelAccount, "Xóa thất bại!");
                    }
                } catch (Exception e) {
                }
            }
        }
    }//GEN-LAST:event_btnDeleteQtActionPerformed

    private void btnViewAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAnsActionPerformed
        selectedIndex = jTableQuestion.getSelectedRow();
        if(listQ.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,
                "Hãy nhập thêm câu hỏi rồi xem!");
        } else if(selectedIndex == -1) {
            JOptionPane.showMessageDialog(rootPane,
                "Hãy chọn dòng có câu hỏi cần xem rồi ấn Xem câu trả lời!");
        } else {
            ViewAnswerJDialog view = new ViewAnswerJDialog(this, rootPaneCheckingEnabled);
            Question q = new Question();
            q = listQ.get(selectedIndex);
            List<Answer> listAsw = new ArrayList<>();
            listAsw = new AnswerDAO().list(q.getQuestion_ID());
            view.getOldAnswerData(q, listAsw.get(0), listAsw.get(1), listAsw.get(2), listAsw.get(3));
            view.setVisible(true);
        }
    }//GEN-LAST:event_btnViewAnsActionPerformed

    private void cbbChapterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbChapterActionPerformed
        if(cbbChapter.getSelectedItem() == "Tất cả"){
            cbbLesson.removeAllItems();
            showLessonCombobox();
        }else{
            int chapter = Integer.parseInt(cbbChapter.getSelectedItem().toString());
            ArrayList<Lesson> listL = new ArrayList<Lesson>();
            listL = new LessonDAO().getListLessonByChapter(chapter);
            cbbLesson.setModel(new DefaultComboBoxModel(listL.toArray()));
        }
    }//GEN-LAST:event_cbbChapterActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddQt;
    private javax.swing.JButton btnDeleteQt;
    private javax.swing.JButton btnEditQt;
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnViewAns;
    private javax.swing.JComboBox<String> cbbChapter;
    private javax.swing.JComboBox<String> cbbLesson;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddAc;
    private javax.swing.JButton jButtonAddChapter;
    private javax.swing.JButton jButtonAddLesson;
    private javax.swing.JButton jButtonAddListAc;
    private javax.swing.JButton jButtonAddQuestion;
    private javax.swing.JButton jButtonAddTest;
    private javax.swing.JButton jButtonDeleteChapter;
    private javax.swing.JButton jButtonDeleteLesson;
    private javax.swing.JButton jButtonDeleteQuestion;
    private javax.swing.JButton jButtonDeleteTest;
    private javax.swing.JButton jButtonEditChapter;
    private javax.swing.JButton jButtonEditLesson;
    private javax.swing.JButton jButtonEditQuestion;
    private javax.swing.JButton jButtonEditTest;
    private javax.swing.JComboBox<String> jComboBoxChapter;
    private javax.swing.JComboBox<String> jComboBoxDiff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelAccount;
    private javax.swing.JPanel jPanelAdminAccount;
    private javax.swing.JPanel jPanelChapter;
    private javax.swing.JPanel jPanelExam;
    private javax.swing.JPanel jPanelLesson;
    private javax.swing.JPanel jPanelListLesson;
    private javax.swing.JPanel jPanelQuestion;
    private javax.swing.JPanel jPanelStatistic;
    private javax.swing.JPanel jPanelStudentAccount;
    private javax.swing.JPanel jPanelTestQuestion;
    private javax.swing.JPanel jPanelTests;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableChapter;
    private javax.swing.JTable jTableLesson;
    private javax.swing.JTable jTableQuestion;
    private javax.swing.JTable jTableQuestions;
    private javax.swing.JTable jTableStudentAc;
    private javax.swing.JTable jTableTeacherAc;
    private javax.swing.JTable jTableTests;
    // End of variables declaration//GEN-END:variables
}
