package View;

import DatabaseIO.AnswerDAO;
import DatabaseIO.ChapterDAO;
import DatabaseIO.LessonDAO;
import DatabaseIO.QuestionDAO;
import Model.Answer;
import Model.Chapter;
import Model.Lesson;
import Model.Question;
import View.AdminForm;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class EditQuestionDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddQuestionDialog
     */
    private AdminForm adminForm;
    
    public EditQuestionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        adminForm = (AdminForm) parent;
        this.setTitle("Sửa thông tin câu hỏi");
        cbLevel.addItem("Dễ");
        cbLevel.addItem("Trung bình");
        cbLevel.addItem("Khó");
    }
    
    public void showChapterCombobox(){
        ArrayList<Chapter> listC = new ArrayList<Chapter>();
        listC = new ChapterDAO().getListChapter();
        for (Chapter chapter : listC) {
            cbbChapter.addItem(String.valueOf(chapter.getChapter()));
        }
    }
    
    private void showLessonByChapterCombobox(){
        int chapter = Integer.parseInt(cbbChapter.getSelectedItem().toString());
        Chapter c = new ChapterDAO().getChapterByChapter(chapter);
        ArrayList<Lesson> listL = new ArrayList<Lesson>();
        listL = new LessonDAO().getListLessonByChapter(c.getChapter_ID());
        cbbLesson.removeAllItems();
        for (Lesson lesson : listL) {
            cbbLesson.addItem(String.valueOf(lesson.getLesson()));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rdbTrue3 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        rdbTrue4 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaAns1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaAns2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        rdbTrue1 = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaAns3 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        rdbTrue2 = new javax.swing.JRadioButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAreaAns4 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbLevel = new javax.swing.JComboBox<>();
        cbbLesson = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbbChapter = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaQuestion = new javax.swing.JTextArea();
        lbID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Hủy");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Sửa câu hỏi");

        buttonGroup1.add(rdbTrue3);
        rdbTrue3.setText("Đáp án đúng");

        jLabel9.setText("Đáp án 4");

        buttonGroup1.add(rdbTrue4);
        rdbTrue4.setText("Đáp án đúng");

        txtAreaAns1.setColumns(20);
        txtAreaAns1.setLineWrap(true);
        txtAreaAns1.setRows(5);
        jScrollPane1.setViewportView(txtAreaAns1);

        txtAreaAns2.setColumns(20);
        txtAreaAns2.setLineWrap(true);
        txtAreaAns2.setRows(5);
        jScrollPane3.setViewportView(txtAreaAns2);

        jLabel6.setText("Đáp án 1:");

        buttonGroup1.add(rdbTrue1);
        rdbTrue1.setText("Đáp án đúng");

        txtAreaAns3.setColumns(20);
        txtAreaAns3.setLineWrap(true);
        txtAreaAns3.setRows(5);
        jScrollPane4.setViewportView(txtAreaAns3);

        jLabel7.setText("Đáp án 2:");

        buttonGroup1.add(rdbTrue2);
        rdbTrue2.setText("Đáp án đúng");

        txtAreaAns4.setColumns(20);
        txtAreaAns4.setLineWrap(true);
        txtAreaAns4.setRows(5);
        jScrollPane5.setViewportView(txtAreaAns4);

        jLabel8.setText("Đáp án 3:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rdbTrue4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rdbTrue3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rdbTrue2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rdbTrue1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbTrue1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbTrue2)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rdbTrue3))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9)
                                            .addComponent(rdbTrue4)))
                                    .addComponent(jLabel8)))
                            .addComponent(jLabel7)))
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        cbLevel.setToolTipText("");
        cbLevel.setName(""); // NOI18N

        jLabel2.setText("Câu hỏi:");

        jLabel5.setText("ID:");

        jLabel3.setText("Độ khó:");

        jLabel4.setText("Bài:");

        cbbChapter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChapterActionPerformed(evt);
            }
        });

        jLabel10.setText("Chương:");

        txtAreaQuestion.setColumns(20);
        txtAreaQuestion.setLineWrap(true);
        txtAreaQuestion.setRows(5);
        jScrollPane2.setViewportView(txtAreaQuestion);

        lbID.setText("ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addComponent(cbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(cbbChapter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(cbbLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbID, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(cbbChapter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbbLesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // cập nhật câu hỏi
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            String question = txtAreaQuestion.getText();
            String answer1 = txtAreaAns1.getText();
            String answer2 = txtAreaAns2.getText();
            String answer3 = txtAreaAns3.getText();
            String answer4 = txtAreaAns4.getText();
            
            if(question.trim().equals("")){
                throw new Exception("Câu hỏi không được để trống!");
            }else if(answer1.trim().equals("") || answer2.trim().equals("")
                    || answer3.trim().equals("") || answer4.trim().equals("")){
                throw new Exception("Câu trả lời không được để trống!");
            }else{
                Question q = new Question();
                q.setQuestion_ID(Integer.parseInt(lbID.getText()));
                q.setQuestion(question);
                q.setLevel(cbLevel.getSelectedIndex() + 1);
                q.setLesson(Integer.valueOf(cbbLesson.getSelectedItem().toString()));

                boolean editQ = new QuestionDAO().updateQuestion(q);
                List<Answer> listAsw = new ArrayList<>();
                listAsw = new AnswerDAO().list(q.getQuestion_ID());
                // thêm câu trả lời 1
                Answer asw1 = new Answer();
                asw1.setAnswer(answer1);
                asw1.setCorrect(rdbTrue1.isSelected());
                asw1.setAnswer_ID(listAsw.get(0).getAnswer_ID());
                // thêm câu trả lời 2
                Answer asw2 = new Answer();
                asw2.setAnswer(answer2);
                asw2.setCorrect(rdbTrue2.isSelected());
                asw2.setAnswer_ID(listAsw.get(1).getAnswer_ID());
                // thêm câu trả lời 3
                Answer asw3 = new Answer();
                asw3.setAnswer(answer3);
                asw3.setCorrect(rdbTrue3.isSelected());
                asw3.setAnswer_ID(listAsw.get(2).getAnswer_ID());
                // thêm câu trả lời 4
                Answer asw4 = new Answer();
                asw4.setAnswer(answer4);
                asw4.setCorrect(rdbTrue4.isSelected());
                asw4.setAnswer_ID(listAsw.get(3).getAnswer_ID());

                boolean editA1 = new AnswerDAO().updateAnswer(asw1);
                boolean editA2 = new AnswerDAO().updateAnswer(asw2);
                boolean editA3 = new AnswerDAO().updateAnswer(asw3);
                boolean editA4 = new AnswerDAO().updateAnswer(asw4);

                if(editQ == editA1 == editA2 == editA3 == editA4 == true){
                    adminForm.showTableQuestion();
                    int dialogResult = JOptionPane.showConfirmDialog(rootPane,
                        "Sửa thành công!", "Thông báo", JOptionPane.DEFAULT_OPTION);
                    if(dialogResult == 0){                    
                        this.dispose();
                    }
                } else{
                    JOptionPane.showMessageDialog(rootPane, "Sửa thất bại!");
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Thông báo!",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed
    // hủy cập nhật
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cbbChapterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbChapterActionPerformed
        showLessonByChapterCombobox();
    }//GEN-LAST:event_cbbChapterActionPerformed
    // lấy dữ liệu cũ của câu hỏi và hiển thị ra 
    public void getOldQuestionData(Question q) {
        lbID.setText(Integer.toString(q.getQuestion_ID()));
        txtAreaQuestion.setText(q.getQuestion());
        cbLevel.setSelectedItem("Dễ");
        if(q.getLevel() == 2){
            cbLevel.setSelectedItem("Trung bình");
        }
        if(q.getLevel() == 3){
            cbLevel.setSelectedItem("Khó");
        }
        Lesson l = new LessonDAO().getLessonByLesson_ID(q.getLesson());
        Chapter c = new ChapterDAO().getChapterByChapter_ID(l.getChapter());
        cbbChapter.setSelectedItem(String.valueOf(c.getChapter()));
        cbbLesson.setSelectedItem(String.valueOf(l.getLesson()));
    }
    // lấy dữ liệu cũ của câu trả lời và hiển thị ra
    public void getOldAnswerData(Answer asw1, Answer asw2, Answer asw3, Answer asw4){
        txtAreaAns1.setText(asw1.getAnswer());
        rdbTrue1.setSelected(asw1.isCorrect());
        txtAreaAns2.setText(asw2.getAnswer());
        rdbTrue2.setSelected(asw2.isCorrect());
        txtAreaAns3.setText(asw3.getAnswer());
        rdbTrue3.setSelected(asw3.isCorrect());
        txtAreaAns4.setText(asw4.getAnswer());
        rdbTrue4.setSelected(asw4.isCorrect());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditQuestionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditQuestionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditQuestionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditQuestionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditQuestionDialog dialog = new EditQuestionDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbLevel;
    private javax.swing.JComboBox<String> cbbChapter;
    private javax.swing.JComboBox<String> cbbLesson;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbID;
    private javax.swing.JRadioButton rdbTrue1;
    private javax.swing.JRadioButton rdbTrue2;
    private javax.swing.JRadioButton rdbTrue3;
    private javax.swing.JRadioButton rdbTrue4;
    private javax.swing.JTextArea txtAreaAns1;
    private javax.swing.JTextArea txtAreaAns2;
    private javax.swing.JTextArea txtAreaAns3;
    private javax.swing.JTextArea txtAreaAns4;
    private javax.swing.JTextArea txtAreaQuestion;
    // End of variables declaration//GEN-END:variables
}
