package View;

import DatabaseIO.AnswerDAO;
import DatabaseIO.QuestionDAO;
import DatabaseIO.QuestionDAO;
import Model.Answer;
import Model.Question;
import View.AdminForm;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class EditQuestionDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddQuestionDialog
     */
    private AdminForm adminForm;
    
    public EditQuestionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        adminForm = (AdminForm) parent;
        this.setTitle("Sửa thông tin câu hỏi");
        cbLevel.addItem("Dễ");
        cbLevel.addItem("Trung bình");
        cbLevel.addItem("Khó");
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtQuestion = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        cbLevel = new javax.swing.JComboBox<>();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rdbTrue1 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        rdbTrue2 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        rdbTrue3 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        rdbTrue4 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaAns1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaAns2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaAns3 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAreaAns4 = new javax.swing.JTextArea();
        cbbLesson = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Độ khó:");

        jLabel4.setText("Bài:");

        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        cbLevel.setToolTipText("");
        cbLevel.setName(""); // NOI18N

        btnCancel.setText("Hủy");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Sửa câu hỏi");

        jLabel2.setText("Câu hỏi:");

        jLabel5.setText("ID:");

        txtID.setEditable(false);
        txtID.setEnabled(false);

        jLabel6.setText("Đáp án 1:");

        buttonGroup1.add(rdbTrue1);
        rdbTrue1.setText("Đáp án đúng");

        jLabel7.setText("Đáp án 2:");

        buttonGroup1.add(rdbTrue2);
        rdbTrue2.setText("Đáp án đúng");

        jLabel8.setText("Đáp án 3:");

        buttonGroup1.add(rdbTrue3);
        rdbTrue3.setText("Đáp án đúng");

        jLabel9.setText("Đáp án 4");

        buttonGroup1.add(rdbTrue4);
        rdbTrue4.setText("Đáp án đúng");

        txtAreaAns1.setColumns(20);
        txtAreaAns1.setLineWrap(true);
        txtAreaAns1.setRows(5);
        jScrollPane1.setViewportView(txtAreaAns1);

        txtAreaAns2.setColumns(20);
        txtAreaAns2.setLineWrap(true);
        txtAreaAns2.setRows(5);
        jScrollPane3.setViewportView(txtAreaAns2);

        txtAreaAns3.setColumns(20);
        txtAreaAns3.setLineWrap(true);
        txtAreaAns3.setRows(5);
        jScrollPane4.setViewportView(txtAreaAns3);

        txtAreaAns4.setColumns(20);
        txtAreaAns4.setLineWrap(true);
        txtAreaAns4.setRows(5);
        jScrollPane5.setViewportView(txtAreaAns4);

        cbbLesson.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtQuestion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                                    .addComponent(txtID, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbLevel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbLesson, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdbTrue4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdbTrue3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdbTrue2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdbTrue1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(77, 77, 77)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbLesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbTrue1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbTrue2)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rdbTrue3))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9)
                                            .addComponent(rdbTrue4)))
                                    .addComponent(jLabel8)))
                            .addComponent(jLabel7)))
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // cập nhật câu hỏi
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            
            Question q = new Question();
            q.setQuestion_ID(Integer.parseInt(txtID.getText()));
            q.setQuestion(txtQuestion.getText());
            q.setLevel(cbLevel.getSelectedIndex() + 1);
            q.setLesson(Integer.parseInt(cbbLesson.getSelectedItem().toString()));
            
            boolean editQ = new QuestionDAO().updateQuestion(q);
            List<Answer> listAsw = new ArrayList<>();
            listAsw = new AnswerDAO().list(q.getQuestion_ID());
            // thêm câu trả lời 1
            Answer asw1 = new Answer();
            asw1.setAnswer(txtAreaAns1.getText());
            asw1.setCorrect(rdbTrue1.isSelected());
            asw1.setAnswer_ID(listAsw.get(0).getAnswer_ID());
            // thêm câu trả lời 2
            Answer asw2 = new Answer();
            asw2.setAnswer(txtAreaAns2.getText());
            asw2.setCorrect(rdbTrue2.isSelected());
            asw2.setAnswer_ID(listAsw.get(1).getAnswer_ID());
            // thêm câu trả lời 3
            Answer asw3 = new Answer();
            asw3.setAnswer(txtAreaAns3.getText());
            asw3.setCorrect(rdbTrue3.isSelected());
            asw3.setAnswer_ID(listAsw.get(2).getAnswer_ID());
            // thêm câu trả lời 4
            Answer asw4 = new Answer();
            asw4.setAnswer(txtAreaAns4.getText());
            asw4.setCorrect(rdbTrue4.isSelected());
            asw4.setAnswer_ID(listAsw.get(3).getAnswer_ID());
            
            boolean editA1 = new AnswerDAO().updateAnswer(asw1);
            boolean editA2 = new AnswerDAO().updateAnswer(asw2);
            boolean editA3 = new AnswerDAO().updateAnswer(asw3);
            boolean editA4 = new AnswerDAO().updateAnswer(asw4);
                       
            if(editQ == editA1 == editA2 == editA3 == editA4 == true){
                adminForm.showTableQuestion();
                int dialogResult = JOptionPane.showConfirmDialog(rootPane,
                    "Sửa thành công!", "Thông báo", JOptionPane.DEFAULT_OPTION);
                if(dialogResult == 0){                    
                    this.dispose();
                }
            } else{
                JOptionPane.showMessageDialog(rootPane, "Sửa thất bại!");
            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btnSaveActionPerformed
    // hủy cập nhật
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed
    // lấy dữ liệu cũ của câu hỏi và hiển thị ra 
    public void getOldQuestionData(Question q) {
        txtID.setText(Integer.toString(q.getQuestion_ID()));
        txtQuestion.setText(q.getQuestion());
        cbLevel.setSelectedItem("Dễ");
        if(q.getLevel() == 2){
            cbLevel.setSelectedItem("Trung bình");
        }
        if(q.getLevel() == 3){
            cbLevel.setSelectedItem("Khó");
        }
        cbbLesson.setSelectedItem(Integer.toString(q.getLesson()));
    }
    // lấy dữ liệu cũ của câu trả lời và hiển thị ra
    public void getOldAnswerData(Answer asw1, Answer asw2, Answer asw3, Answer asw4){
        txtAreaAns1.setText(asw1.getAnswer());
        rdbTrue1.setSelected(asw1.isCorrect());
        txtAreaAns2.setText(asw2.getAnswer());
        rdbTrue2.setSelected(asw2.isCorrect());
        txtAreaAns3.setText(asw3.getAnswer());
        rdbTrue3.setSelected(asw3.isCorrect());
        txtAreaAns4.setText(asw4.getAnswer());
        rdbTrue4.setSelected(asw4.isCorrect());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditQuestionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditQuestionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditQuestionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditQuestionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditQuestionDialog dialog = new EditQuestionDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbLevel;
    private javax.swing.JComboBox<String> cbbLesson;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JRadioButton rdbTrue1;
    private javax.swing.JRadioButton rdbTrue2;
    private javax.swing.JRadioButton rdbTrue3;
    private javax.swing.JRadioButton rdbTrue4;
    private javax.swing.JTextArea txtAreaAns1;
    private javax.swing.JTextArea txtAreaAns2;
    private javax.swing.JTextArea txtAreaAns3;
    private javax.swing.JTextArea txtAreaAns4;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtQuestion;
    // End of variables declaration//GEN-END:variables
}
